### PR TITLE
feat: Get by name

### LINKED ISSUE #5: do we want a "get" variant by name function?
something like:

```go
func Get(variant string) Theme {
	for _, t := range []Theme{
		Mocha,
		Frappe,
		Macchiato,
		Latte,
	} {
		if t.Name() == variant {
			return t
		}
	}
	return nil
}
```

Not sure if it makes sense or not... wonder what y'all think

### PR DESCRIPTION
**Pull request by caarlos0**
Not sure about the func name, let me know what you think!

closes #5

### CODE REVIEW

**Comment by jolheiser** [comment]
What about `Variant`?

`catppuccin.Get("mocha")` vs  `catppuccin.Variant("mocha")`

**Comment by kkrypt0nn** [comment]
I'd rather go for `Variant` as well, that's the way it is [already named](https://github.com/catppuccin/go/blob/178f1a06d65a53f7fe3d7d352f841dad2006e47f/macchiato.go#L6) and use [`name`](https://github.com/catppuccin/go/blob/178f1a06d65a53f7fe3d7d352f841dad2006e47f/macchiato.go#L9) as parameter of the function, such as
```go
func Variant(name string) Theme {}
```
would be more fitting. Though using `flavour` might be better, see #7

**Comment by caarlos0** [comment]
I can't call the function just `Flavour` as it will conflict with the type with the same name...

Some options:
- `catppuccin.Get`
- `catppuccin.Find`
- `catppuccin.ByName`

**Comment by kkrypt0nn** [comment]
> I can't call the function just `Flavour` as it will conflict with the type with the same name...

What I meant was the parameter name to be `flavour` instead of `name`
```go
func Variant(flavour string) Flavour {}
```

`Get()` is fine but sort of vague so preferably wouldn't use it.
For `Find()`/`ByName()` I'd eventually put them together as `FindByName()`.

**Comment by caarlos0** [comment]
done @kkrypt0nn

**Comment by kkrypt0nn** [comment]
Looking nice 👍

**Pull request merged**
